version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/app_db?schema=public
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./prisma:/app/prisma
      - ./next.config.ts:/app/next.config.ts
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./.env:/app/.env
      - ./postcss.config.mjs:/app/postcss.config.mjs
      - ./eslint.config.mjs:/app/eslint.config.mjs
    depends_on:
      - db
    command: npm run dev

volumes:
  postgres_data:
