# =========================================================================
# CONFIGURAÇÕES OBRIGATÓRIAS DO SONARCLOUD (Copie os valores do seu painel)
# =========================================================================
sonar.projectKey=ignite
sonar.organization=ignite

# Informações básicas do projeto
sonar.projectName=Ignite
sonar.projectVersion=1.0

# =========================================================================
# CONFIGURAÇÕES DE ANÁLISE E COBERTURA
# =========================================================================
# Onde estão os arquivos de código-fonte principais?
sonar.sources=src

# Onde estão os arquivos de teste? (usados para cobertura, não para buscar code smells)
sonar.tests=__tests__

# Padrão de nomenclatura para não misturar código com teste
sonar.test.inclusions=__tests__/**/*.test.ts,src/**/*.test.ts

# Ignorar pastas que não precisam ser validadas pelo Sonar (scripts, DB, dependências)
sonar.exclusions=node_modules/**, scripts/**, prisma/**, .github/**, **/*.test.ts, **/*.spec.ts
